### ISSUE TITLE
crossplatform

### ISSUE THREAD

**Issue by grylem** [plzombie/all2ppm#1]
Здравствуйте.
Можете сделать вашу программу кроссплатформенной?
Спасибо.

**Comment by plzombie** [comment]
Здравствуйте. Займусь в выходные

**Comment by plzombie** [comment]
Теперь компилируется под linux. Добавил мейкфайл заодно

**Comment by grylem** [comment]
Спасибо.
В файле all2pbm нужна небольшая косметическая правка
all2ppm input.* output.ppm
на
all2pbm input.* output.pbm

**Comment by plzombie** [comment]
Исправил

**Comment by grylem** [comment]
Спасибо.
